// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/auth/oauth2callback.ts";
import * as $5 from "./routes/auth/signin.ts";
import * as $6 from "./routes/auth/signout.ts";
import * as $7 from "./routes/chat.ts";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/manage/dump.ts";
import * as $10 from "./routes/manage/reset.ts";
import * as $11 from "./routes/skyway/token.ts";
import * as $12 from "./routes/upload/files/[id].ts";
import * as $13 from "./routes/upload/index.ts";
import * as $$0 from "./islands/ChatArea.tsx";
import * as $$1 from "./islands/VideoArea.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/auth/oauth2callback.ts": $4,
    "./routes/auth/signin.ts": $5,
    "./routes/auth/signout.ts": $6,
    "./routes/chat.ts": $7,
    "./routes/index.tsx": $8,
    "./routes/manage/dump.ts": $9,
    "./routes/manage/reset.ts": $10,
    "./routes/skyway/token.ts": $11,
    "./routes/upload/files/[id].ts": $12,
    "./routes/upload/index.ts": $13,
  },
  islands: {
    "./islands/ChatArea.tsx": $$0,
    "./islands/VideoArea.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
